// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgunhiyxysetdilqtsns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpndW5oaXl4eXNldGRpbHF0c25zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDgxMDYsImV4cCI6MjA2NDA4NDEwNn0.fTZ6eTzE2zlWumKMFgWnazMaMnFY45AruBpqjRzC-eg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);